<h1>Импорт библиотек

In [54]:
import numpy as np
import matplotlib.pyplot as plt
import sys

np.set_printoptions(threshold=sys.maxsize, linewidth=sys.maxsize)

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [ ]:
def sum_prod(X, V):
    '''
    X - матрицы (n, n)
    V - векторы (n, 1)
    Гарантируется, что len(X) == len(V)
    '''
    # Your code goes here
    result = np.zeros((X.shape[2], 1))
    
    for i in range(len(X)):
        for k in range(X.shape[1]):
            for j in range(X.shape[2]):
                result[k, 0] += V[i, k, 0] * X[i, k, j]

    return result

n = 5
X = np.random.randint(0, 2, (3, n, n))

V = np.random.randint(0, 2, (3, n, 1))


print(f'X:\n{X}\nv:\n{V}')
print(f'result:\n{sum_prod(X, V)}')

X:
[[[1 1 1 0 1]
  [0 0 1 0 0]
  [1 1 0 0 1]
  [0 1 1 0 0]
  [1 0 0 0 1]]

 [[0 0 0 0 0]
  [1 1 0 1 1]
  [0 1 1 0 1]
  [1 1 0 0 1]
  [1 0 0 0 0]]

 [[1 0 0 1 0]
  [0 0 0 0 0]
  [1 0 1 0 0]
  [1 1 0 1 1]
  [1 1 1 1 1]]]
v:
[[[0]
  [1]
  [0]
  [0]
  [1]]

 [[1]
  [0]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]
  [0]]]
result:
[[2.]
 [1.]
 [5.]
 [7.]
 [3.]]


<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [ ]:

def binarize(M, threshold=0.5):
    # Your code goes here
    result = np.empty((M.shape[0], M.shape[1]))
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            result[i, j] = 1 if M[i, j] > threshold else 0

    return result

M = np.random.randint(0, 8, (2, 6))
print(M)
print(binarize(M, 4))

[[5 1 5 4 1 4]
 [5 1 5 4 5 6]]
[[1. 0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 1. 1.]]


<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [ ]:
def unique_rows(mat):
    # Your code goes here
    for i in range(mat.shape[0]):
        yield np.unique(mat[i])


def unique_columns(mat):
    # Your code goes here
    for j in range(mat.shape[1]):
        yield np.unique(mat[:, j])


mat = np.random.randint(0, 9, (10, 10))

print(mat)
generator_r = unique_rows(mat)
generator_c = unique_columns(mat)

print('\nrows\n')
for unique_row in generator_r:
    print(unique_row)

print('\ncolumn\n')
for unique_column in generator_c:
    print(unique_column)


[[6 5 8 1 2 1 4 3 2 1]
 [1 6 0 5 7 5 1 1 4 5]
 [3 2 4 4 5 5 2 6 1 3]
 [5 1 6 1 0 7 6 8 3 6]
 [6 1 1 5 4 1 0 1 0 3]
 [1 4 8 5 4 5 8 8 0 0]
 [5 5 2 6 4 2 5 7 0 3]
 [1 2 2 3 5 1 0 7 0 4]
 [4 6 6 5 3 1 1 3 1 4]
 [5 8 8 7 8 3 6 5 4 6]]

rows

[1 2 3 4 5 6 8]
[0 1 4 5 6 7]
[1 2 3 4 5 6]
[0 1 3 5 6 7 8]
[0 1 3 4 5 6]
[0 1 4 5 8]
[0 2 3 4 5 6 7]
[0 1 2 3 4 5 7]
[1 3 4 5 6]
[3 4 5 6 7 8]

column

[1 3 4 5 6]
[1 2 4 5 6 8]
[0 1 2 4 6 8]
[1 3 4 5 6 7]
[0 2 3 4 5 7 8]
[1 2 3 5 7]
[0 1 2 4 5 6 8]
[1 3 5 6 7 8]
[0 1 2 3 4]
[0 1 3 4 5 6]


<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [79]:
# Your code goes here
def random_mat(M, loc=0, scale=1):
    M = np.random.normal(loc, scale, (M.shape))
    return M

M = np.empty((2, 10))
print(random_mat(M))

[[ 2.07328749 -0.5550071  -0.67131446 -0.59664703  0.31278206 -0.1694633   1.32898112 -1.449379    0.15972562  1.20469685]
 [ 1.27860668  0.9695193  -0.84148235  0.03565207  0.50856211  1.00389707 -0.81788722 -0.30437616  0.03336555  0.40774341]]


<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [82]:
def chess(m, n, a, b):
    # Your code goes here
    M = np.full((m, n), a)
    for i in M.shape[0]:
        for j in M.shape[1]:
            M[i, j] = a if (i % 2 == 0 and j % 2 == 0) or (i % 2 == 1 and j % 2 == 1) else b
    return M

print(chess(3, 4, 2, 1))

TypeError: 'int' object is not iterable

<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [ ]:
def draw_rectangle(a, b, m, n, rectangle_color, background_color):
    # Your code goes here
    pass

def draw_ellipse(a, b, m, n, ellipse_color, background_color):
    # Your code goes here
    pass

<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [ ]:
# Your code goes here

<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [ ]:
# Your code goes here